### ISSUE TITLE
Release to Rubygems

### ISSUE THREAD

**Issue by jweisman** [UW-Madison-Library/bibcard#3]
Hi there. Great library- thanks! It would be very helpful to have this in Rubygems to ease installation. I had to go through a few hoops to deploy this as a [serverless API in AWS](https://github.com/jweisman/primo-explore-lod-author-card/tree/master/serverless-bibcard). 

Any plans to do so in the near future?

**Comment by steve-meyer** [comment]
Hi Josh, thanks for the friendly push (pun intended) to get this in RubyGems. This is something we have wanted to do for a while and we finally pushed it up. Note that I also took the opportunity to deal with a few warning messages and dependency updates for Ruby 2.7.

**Comment by jweisman** [comment]
Thanks Steve! This makes my [dependencies](https://github.com/jweisman/primo-explore-lod-author-card/commit/68acd3dc55b2e8d86e74ce7e56dd22e2d7123722#diff-92cce540abadcbe5ca9acda1a76b00cb8bdd4d80ee2c3ce5cc8b6cc660ad69f9L1) much cleaner.

I've updated the [Serverless API wrapper](https://github.com/jweisman/primo-explore-lod-author-card/tree/master/serverless-bibcard), as seen in this [example](https://api.exldevnetwork.net/bibcard/?uri=http://id.loc.gov/authorities/names/n2008054754).
